<div class="panel panel-body text-center">
        @if($progress_type===\App\Main::PROGRESS_INDUSTRY)
                <div class="col-xs-2"><a href="{{ url('process1') }}{{getMainProgressLink(1,$progress_type)}}" class="btn btn-block {{$progressNo===1?'arrow-default':'arrow-right'}} {{$progressNo>1?'arrow-outline-success':''}}">เริ่ม</a></div>
                <div class="col-xs-1"><a href="{{ url('process2') }}{{getMainProgressLink(2,$progress_type)}}" class="btn btn-block {{$progressNo===2?'arrow-default':getMainProgressProp(2, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(2, $progress_type, '','disabled')}}>2</a></div>
                <div class="col-xs-1"><a href="{{ url('process3') }}{{getMainProgressLink(3,$progress_type)}}" class="btn btn-block {{$progressNo===3?'arrow-default':getMainProgressProp(3, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(3, $progress_type, '','disabled')}}>3</a></div>
                <div class="col-xs-1"><a href="{{ url('process4') }}{{getMainProgressLink(4,$progress_type)}}" class="btn btn-block {{$progressNo===4?'arrow-default':getMainProgressProp(4, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(4, $progress_type, '','disabled')}}>4</a></div>
                <div class="col-xs-1"><a href="{{ url('process5') }}{{getMainProgressLink(5,$progress_type)}}" class="btn btn-block {{$progressNo===5?'arrow-default':getMainProgressProp(5, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(5, $progress_type, '','disabled')}}>5</a></div>
                <div class="col-xs-1"><a href="{{ url('process6') }}{{getMainProgressLink(6,$progress_type)}}" class="btn btn-block {{$progressNo===6?'arrow-default':getMainProgressProp(6, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(6, $progress_type, '','disabled')}}>6</a></div>
                <div class="col-xs-1"><a href="{{ url('process7') }}{{getMainProgressLink(7,$progress_type)}}" class="btn btn-block {{$progressNo===7?'arrow-default':getMainProgressProp(7, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(7, $progress_type, '','disabled')}}>7</a></div>
                <div class="col-xs-1"><a href="{{ url('process8') }}{{getMainProgressLink(8,$progress_type)}}" class="btn btn-block {{$progressNo===8?'arrow-default':getMainProgressProp(8, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(8, $progress_type, '','disabled')}}>8</a></div>
                <div class="col-xs-1"><a href="{{ url('process9') }}{{getMainProgressLink(9,$progress_type)}}" class="btn btn-block {{$progressNo===9?'arrow-default':getMainProgressProp(9, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(9, $progress_type, '','disabled')}}>9</a></div>
                <div class="col-xs-2"><a href="{{ url('process10') }}{{getMainProgressLink(10,$progress_type)}}" class="btn btn-block {{$progressNo===10?'btn-default':getMainProgressProp(10, $progress_type, 'btn-outline-success','btn-outline-default')}}" {{getMainProgressProp(10, $progress_type, '','disabled')}}>เสร็จสิ้น</a></div>
        @elseif($progress_type===\App\Main::PROGRESS_BUILDING)
                <div class="col-xs-2"><a href="{{ url('building/process1') }}{{getMainProgressLink(1,$progress_type)}}" class="btn btn-block {{$progressNo===1?'arrow-default':'arrow-right'}} {{$progressNo>1?'arrow-outline-success':''}}">เริ่ม</a></div>
                <div class="col-xs-1"><a href="{{ url('building/process2') }}{{getMainProgressLink(2,$progress_type)}}" class="btn btn-block {{$progressNo===2?'arrow-default':getMainProgressProp(2, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(2, $progress_type, '','disabled')}}>2</a></div>
                <div class="col-xs-1"><a href="{{ url('building/process3') }}{{getMainProgressLink(3,$progress_type)}}" class="btn btn-block {{$progressNo===3?'arrow-default':getMainProgressProp(3, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(3, $progress_type, '','disabled')}}>3</a></div>
                <div class="col-xs-1"><a href="{{ url('building/process4') }}{{getMainProgressLink(4,$progress_type)}}" class="btn btn-block {{$progressNo===4?'arrow-default':getMainProgressProp(4, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(4, $progress_type, '','disabled')}}>4</a></div>
                <div class="col-xs-1"><a href="{{ url('building/process5') }}{{getMainProgressLink(5,$progress_type)}}" class="btn btn-block {{$progressNo===5?'arrow-default':getMainProgressProp(5, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(5, $progress_type, '','disabled')}}>5</a></div>
                <div class="col-xs-1"><a href="{{ url('building/process6') }}{{getMainProgressLink(6,$progress_type)}}" class="btn btn-block {{$progressNo===6?'arrow-default':getMainProgressProp(6, $progress_type, 'arrow-right arrow-outline-success','arrow-right arrow-outline-default')}}" {{getMainProgressProp(6, $progress_type, '','disabled')}}>6</a></div>
                <div class="col-xs-2"><a href="{{ url('building/process7') }}{{getMainProgressLink(7,$progress_type)}}" class="btn btn-block {{$progressNo===7?'btn-default':getMainProgressProp(7, $progress_type, 'btn-outline-success','btn-outline-default')}}" {{getMainProgressProp(7, $progress_type, '','disabled')}}>เสร็จสิ้น</a></div>
        @endif
</div>